### ISSUE TITLE
shell-command-on-region error occurred in cppcm-get-exe-path-current-buffer

### ISSUE THREAD

**Issue by EnjoyYouth** [redguardtoo/emacs.d#725]
![cppcm_gdb](https://user-images.githubusercontent.com/39292754/46522857-81acf900-c8b6-11e8-9257-8fdf646f99e5.png)
emacs version:  25.2.2
OS: ubuntu 18.04.1
cppcm-cmake version:  0.5.5
xsel version: 1.2.0

**Comment by redguardtoo** [comment]
install `xsel`, this command copy path to clipboard.

**Comment by EnjoyYouth** [comment]
I have installed xsel

**Comment by EnjoyYouth** [comment]
what i want to say is that:
 I do install xsel, but it does not work.

**Comment by redguardtoo** [comment]
`which xsel` in shell, should get output `/usr/bin/xsel`.

`M-x eval-expression ENT`, then `(cppcm-share-str "hello")`, what happened?

**Comment by EnjoyYouth** [comment]
I don't have a computer right now, I am afraid I will reply the message tomorrow.

**Comment by EnjoyYouth** [comment]
`which xsel` in shell, I get output `/usr/bin/xsel`.
then, `M-x eval-expression ENT (cppcm-share-str "hello")` give this message:
`read--expression: Trailing garbage following expression`

**Comment by EnjoyYouth** [comment]
It's my fault.I should involve `M-x eval-expression ENT` at first ,then` M-x eval-expression (cppcm-share-str "hello")`, right?
but  `M-x eval-expression ENT` give this message:
![1](https://user-images.githubusercontent.com/39292754/46565615-ac915e80-c943-11e8-8bf7-0b5b6206f415.png)
then ` M-x eval-expression (cppcm-share-str "hello")` give this message:
`eval: Symbol’s function definition is void: cppcm-share-str`

**Comment by redguardtoo** [comment]
` cppcm-get-exe-path-current-buffer` copy the exe path to clipboard. I wil copy it to `kill-ring` instead and provides callback to clipboard function which is provided by user.

**Comment by EnjoyYouth** [comment]
I don't understand.   **provides callback to clipboard function which is provided by user** mean what?

**Comment by redguardtoo** [comment]
fixed in `cpputils-cmake v0.5.8`

**Comment by EnjoyYouth** [comment]
I tried it, but still exist some problems.
I enable `toggle-debug-on-quit` ,then execute `cppcm-get-exe-path-current-buffer`, it get stucked, so i C-g, then i get this message:
![4](https://user-images.githubusercontent.com/39292754/46567758-43bddc80-c96b-11e8-9e3e-5af1de657dae.png)


`M-x eval-expression ENT` give this message:
![3](https://user-images.githubusercontent.com/39292754/46567655-dd37bf00-c968-11e8-9ab1-b54dc1ba6d8b.png)
`M-x eval-expression (cppcm-share-str "hello")` get stucked, `toggle-debug-on-quit` just give this message:`(Shell command failed with error)`
And ` cppcm-get-exe-path-current-buffer` still work very well under terminal.

**Comment by EnjoyYouth** [comment]
Btw, i can't update cppcm-make Emacs package manager. So, i download and replace cpputils-cmake.el. then restart emacs.

**Comment by redguardtoo** [comment]
use melpa , see https://melpa.org/#/cpputils-cmake

**Comment by EnjoyYouth** [comment]
It works fine.Thank you.
